#services:
#  postgres:
#    container_name: postgres
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: aniket
#      POSTGRES_PASSWORD: 2004
#      POSTGRES_DB: jwt_security
#      PG_DATA: /data/postgres
#    volumes:
#      - postgres-jwt-security:/data/postgres
#    ports:
#      - "5432:5432"
#    networks:
#      - postgres
##    restart: unless-stopped
#
##  pgadmin:
##    container_name: pgadmin
##    image: dpage/pgadmin4
##    environment:
##      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
##      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
##      PGADMIN_CONFIG_SERVER_MODE: 'False'  # Run in desktop mode
##    volumes:
##      - pgadmin:/var/lib/pgadmin
##    ports:
##      - "5050:80"
##    networks:
##      - postgres
##    restart: unless-stopped
#
#
#networks:
#  postgres:
#    driver: bridge
#
#volumes:
#  postgres-jwt-security:
#  pgadmin:
